/**
 * AUTO-GENERATED — DO NOT EDIT MANUALLY
 *
 * Generated by: npm run images:process
 * Source: data/wallpapers-source/
 *
 * Each entry corresponds to a source image that was processed into
 * AVIF + WebP at 1920w, 2560w, and 3840w sizes in public/wallpapers/.
 */

export interface GeneratedWallpaper {
  /** Unique ID derived from source filename (kebab-case) */
  id: string;
  /** Human-readable display name (auto-generated from filename) */
  name: string;
  /** Primary AVIF URL (1920w default size) */
  url: string;
  /** WebP fallback URL (1920w default size) */
  urlWebp: string;
}

/**
 * All available wallpapers, dynamically generated from source images.
 * The number of entries here directly determines the number of Premium themes.
 */
export const GENERATED_WALLPAPERS: GeneratedWallpaper[] = [
  {
    id: 'bangkok-sunset',
    name: 'Bangkok Sunset',
    url: '/wallpapers/bangkok-sunset-1920w.avif',
    urlWebp: '/wallpapers/bangkok-sunset-1920w.webp',
  },
];
